[package]
name = "phira-mp-client"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
anyhow = "1.0"
chrono = "0.4.26"
dashmap = "5.4.0"
phira-mp-common = { path = "../phira-mp-common" }
tokio = "*"
tracing = "0.1.37"
uuid = { version = "1.3.3", features = ["v4"] }
